name: Test Stuff
on:
    workflow_dispatch:
jobs:
    tests:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macos-14]
          mode: ['debug', 'release']
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Linux Install LLVM and Clang
          if: runner.os == 'Linux'
          uses: KyleMayes/install-llvm-action@v2
          with:
            version: "17.0"
        - name: macOS Install LLVM and Clang
          if: runner.os == 'macOS'
          uses: KyleMayes/install-llvm-action@v2.0.3
          with:
            version: "17.0"
            arch: "arm64"
        - name: Setup MSVC
          if: runner.os == 'Windows'
          uses: ilammy/msvc-dev-cmd@v1
        - name: Setup xmake
          uses: xmake-io/github-action-setup-xmake@v1
          with:
             xmake-version: latest
        - name: xmake config
          run: |
               xmake f -m "${{matrix.mode}}" -y
               xmake build
               xmake test
        
            
